export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAIL = 'SEND_ORDER_FAIL';
export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
